### ISSUE TITLE
不是很了解编译过程（openCV和Cmake）

### ISSUE THREAD

**Issue by Gpeter28** [yifeiyin/pvz-auto-click#1]
新手 刚接触Cmake，捣鼓了一下午没弄懂，希望指点一下。（有了openCV之后怎么和程序中的cmake一起编译）

**Comment by yifeiyin** [comment]
有了 OpenCV 之后，应该能够直接运行，因为已经写在 cmake 文件里了。

```
$ cd pvz-auto-click          # switch the the project directory
$ cmake .                    # run cmake once, against the current dir
$ make                       # this will generate the executable
$ ./pvz-auto-click           # run the executable
```

刚刚又改了几个 bug，要不然还运行不了，现在应该可以了。有问题发截图吧，有可能是我的程序有问题，而不是编译问题。

**Comment by Gpeter28** [comment]
> 有了 OpenCV 之后，应该能够直接运行，因为已经写在 cmake 文件里了。
> 
> ```
> $ cd pvz-auto-click          # switch the the project directory
> $ cmake .                    # run cmake once, against the current dir
> $ make                       # this will generate the executable
> $ ./pvz-auto-click           # run the executable
> ```
> 
> 刚刚又改了几个 bug，要不然还运行不了，现在应该可以了。有问题发截图吧，有可能是我的程序有问题，而不是编译问题。

**Comment by Gpeter28** [comment]
我把cmake弄出来之后 变成这样 
![image](https://user-images.githubusercontent.com/42987392/60769360-40759e00-a101-11e9-99b1-2b9ffb3dc104.png)

但是我不是很清楚这一步。。（build里有opencv-config.cmake）
![image](https://user-images.githubusercontent.com/42987392/60769358-35227280-a101-11e9-89a4-894e73014d1e.png)   
我试过这样 
![image](https://user-images.githubusercontent.com/42987392/60769386-98aca000-a101-11e9-99cb-66f84c1e5245.png)

**Comment by Gpeter28** [comment]
已经解决这个问题了 但是现在会出现这种情况
![image](https://user-images.githubusercontent.com/42987392/60769615-9730a700-a104-11e9-8238-3b472d5dbe3c.png)

**Comment by Gpeter28** [comment]
已解决 感谢
