### ISSUE TITLE
不知道为什么 我编译之后会显示这些

### ISSUE THREAD

**Issue by AnotherGP** [yifeiyin/pvz-auto-click#3]
![image](https://user-images.githubusercontent.com/53016380/61398510-b4345980-a8fe-11e9-8de2-d6fb4bef76b9.png)
![image](https://user-images.githubusercontent.com/53016380/61398518-b991a400-a8fe-11e9-9b4b-e14b107d2d1e.png)
![image](https://user-images.githubusercontent.com/53016380/61398522-bd252b00-a8fe-11e9-926b-e4a409b16403.png)
![image](https://user-images.githubusercontent.com/53016380/61398531-c0201b80-a8fe-11e9-96d7-dcd1fdf585b7.png)
找了很多解决方法都不行 希望能解决下 谢谢

**Comment by yifeiyin** [comment]
呃。。。我时间能力也有限，我最开始使用 Qt 编译的，现在用 cmake 也可以运行起来，具体 setup 的细节我也不是全都明白。而且如果你是想在 Windows 上运行的话，很抱歉的告诉你，不改代码的情况下（就算能编译）也是运行不起来的，因为用了一些 macOS 的命令行工具进行截图、移动鼠标。自己有兴趣、时间的话，可以自己新建一个项目，自己实现一下那些功能，然后直接用我写的程序逻辑，应该是能用的，计算部分基本没有什么硬编码的数据。当然了，前提是你能大概看懂代码，我函数变量名起的还算ok，看不懂的可以问我。
